### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by otsha** [Rsl1122/Forum-Aurum#1]
**Ladattu: 22.4.2018 22:32**

## Toiminnallisuus
- Ensimmäinen huomio: Ulkoasu on todella nätti ja looginen!
- Käyttäjätilin luominen ja sisäänkirjautuminen onnistuvat.
- Kaikki vierailijaroolille määritellyt toiminnot on toteutettavissa.
- Olisi hyvä, jos sovelluksessa olisi testikäyttöön tarkoitetut moderaattori- tai admin-tason tunnukset!

## Käytettävyys
- Kursorin siirtäminen alueen tai langan ylle ei anna minkäänlaista indikaatiota klikattavuudesta. Muilta osin käytettävyydessä ei valittamista!
- Alueelta viimeisen viestin poistamisen jälkeen alueelle siirtyminen aiheuttaa internal server errorin.
- Poistettuun lankaan on edelleenkin mahdollista päästä linkin kautta. Kummituslankaan kommentoiminen tekee kommentista langan ensimmäisen viestin.

## Lähdekoodi
- Lähdekoodin luokittelu koodin toiminnallisuuden mukaan eikä sovelluksen loppukäytön asiayhteyden mukaan vaikuttaa kurssin esimerkkejä loogisemmalta toimintatavalta.
- Koodin kommentoinnissa on runsaasti parantamisen varaa. Nyt kommentteja ei ole kuin pari.
- Lähdekoodi on kuitenkin siistiä, hyvin formatoitua ja metodien nimentä on selkeää.

**Comment by Rsl1122** [comment]
> Olisi hyvä, jos sovelluksessa olisi testikäyttöön tarkoitetut moderaattori- tai admin-tason tunnukset!

Tosiaan ensimmäinen luotu käyttäjä on admin tason käyttäjä (Joten localhost testaus on mahdollista), mutta moderaattori ominaisuudet ovat vielä kesken joten todennäköisesti missasit vain piilotetut alueet sekä alueiden luomisen (Jossa voi valita ryhmän joka näkee alueen)

----

>Kursorin siirtäminen alueen tai langan ylle ei anna minkäänlaista indikaatiota klikattavuudesta. Muilta osin käytettävyydessä ei valittamista!

Näköjään täytyy lisätä vähän css että saa klikkaus hiiren `.nimi { cursor: pointer; }`, kiitos huomiosta.

----

> Alueelta viimeisen viestin poistamisen jälkeen alueelle siirtyminen aiheuttaa internal server errorin.

Neat, enpä hoksannut testata.
Täytyy alkaa poistamaan lanka jos eka viesti poistetaan. :)

----

> Lähdekoodin luokittelu koodin toiminnallisuuden mukaan eikä sovelluksen loppukäytön asiayhteyden mukaan vaikuttaa kurssin esimerkkejä loogisemmalta toimintatavalta.

Luulen että esimerkkien jakotapa on valittu modulaarisuuden vuoksi, jolloin eri paketteja (eli sivuja) voi vain poistaa tai lisätä helposti samasta paketista.

Tämän projektin jakotavalla on helppo työskennellä yhden asian parissa, mm. jos yksi bugi on eksynyt kaikkiin samanlaisiin palasiin, mutta poistamisessa on suurempi työ.
