### ISSUE TITLE
Koodikatselmointi 2

### ISSUE THREAD

**Issue by dennsva** [Rsl1122/Forum-Aurum#2]
Ladattu pe 4.5. klo 19:37

Ensimmäinen huomioni on, että koko projektin ulkoasu on erittäin vakuuttava. Pidän erityisesti ikoneiden käytöstä sekä siitä, että joka viestiketjun kohdalla näkyy sen polku. Olen itse paininut tunteja juuri saadakseni ulkoasusta siedettävän, mutta sinulla homma toimii erinomaisesti selkeällä ja tiiviillä koodilla. Siinäkin taitaa olla tunteja takana. :D

Stats-osio on myös erinomainen ja hot topicin etsintä on hauska lisä tähän kaikkeen. Voisiko siinä olla linkki?

Koodi on mielestäni suurilta osin moitteeton. Kansion views/topicsin metodit edit_msg_page ja edit_msg voit halutessasi yhdistää siten, että metodi tarkistetaan if-lauseella, mutta tämänkin hyödyllisyys on tulkinnanvaraista.

Olet korjannut edellisen palautteen jutut, hyvä!

Jos haluat vielä lisätä foorumiin toiminnallisuutta, voisi jonkinlainen hakutoiminnallisuus olla hyödyllinen. Vastaavasti kaikkien topicien listaus samaan paikkaan voisi olla kätevä, jos käyttäjä ei esimerkiksi muista millä alueella tietty topic oli.

Kaiken kaikkiaan huikea projekti.

**Comment by Rsl1122** [comment]
Ajattelin että tuo edit_msg_page ja edit_msg erottelu on parempi single responsibility mallia toteuttava ratkaisu. 

Jos on if-else block voidaan aina sisälle jäävä koodi eristää omiin metodeihinsa - tässä on jätetty myös if else kokonaan flaskin hoidettavaksi.

Mietin tuota linkkiä yhdessä välissä mutta se vaatisi alueen nimen haun lisäämistä jo nyt kolmea taulua käyttävään kyselyyn joten jätin sen pois (työmäärä > hyöty). Saatan silti kokeilla jos innostun. 

Pagination ajattelin vielä lisätä ensi viikolla. 

Jos ikonit kiinnostaa niin Font Awesome on hyvä, ilmainen ja helppokäyttöinen kirjasto. Suosittelen. 

Kiitos palautteesta! :)
